# Generated by Django 3.2.6 on 2021-09-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default=False, max_length=900),
            preserve_default=False,
        ),
    ]
