# Generated by Django 3.2.6 on 2021-09-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_type',
            new_name='delivery_home',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_temple',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
