# Generated by Django 3.2.6 on 2021-09-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_delivery_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_home',
            field=models.CharField(default='False', max_length=900),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_temple',
            field=models.CharField(default='False', max_length=900),
        ),
    ]
