# Generated by Django 3.2.6 on 2021-09-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210907_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_home',
            field=models.CharField(blank=True, default='False', max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_temple',
            field=models.CharField(blank=True, default='False', max_length=900, null=True),
        ),
    ]
